version: '3.8'
services:
  postgres-staging:
    image: postgres:14
    container_name: postgres-staging
    restart: unless-stopped

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha_segura_aqui
      - POSTGRES_DB=projetogran
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - projetogran_crewflow-network

networks:
  projetogran_crewflow-network:
    external: true

volumes:
  postgres-data: