version: '3.8'
# trigger deploy (no functional change)
services:
  app:
    image: crewflow-app:latest
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NODE_ENV=production
    container_name: crewflow-app-production
    restart: unless-stopped
    networks:
      - projetogran_crewflow-network
    depends_on:
      - postgres-prod

  postgres-prod:
    image: postgres:15
    container_name: postgres-prod
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - projetogran_crewflow-network

  pgadmin-production:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-production
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - projetogran_crewflow-network
    depends_on:
      - postgres-prod

networks:
  projetogran_crewflow-network:
    external: true

volumes:
  postgres_data:
  pgadmin_data: