services:
  postgres-staging:
    image: postgres:15
    container_name: postgres-staging
    restart: unless-stopped

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-staging-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - projetogran_crewflow-network

  pgadmin-staging:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-staging
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5051:80"
    volumes:
      - pgadmin-staging-data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - projetogran_crewflow-network
    depends_on:
      - postgres-staging

networks:
  projetogran_crewflow-network:
    external: true

volumes:
  postgres-staging-data:
  pgadmin-staging-data:
